apiVersion: v1
kind: ServiceAccount
metadata:
  name: authservice
  namespace: oidc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: authn-delegator
rules:
- apiGroups:
    - authentication.k8s.io
  resources:
    - tokenreviews
  verbs:
    - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: authn-delegators
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: authn-delegator
subjects:
  - kind: ServiceAccount
    name: authservice
    namespace: oidc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authservice-pvc
  namespace: oidc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: oidc-authservice-client
  namespace: oidc
type: Opaque
data:
  CLIENT_ID: bWluaW8tY2xpZW50LWFwcA==
  CLIENT_SECRET: bWluaW8tY2xpZW50LWFwcC1zZWNyZXQ=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oidc-authservice-parameters
  namespace: oidc
data:
  OIDC_PROVIDER: http://dex.auth.svc.cluster.local:5556/dex
  OIDC_AUTH_URL: /dex/auth
  OIDC_SCOPES: openid email groups profile
  AUTHSERVICE_URL_PREFIX: /authservice/
  SKIP_AUTH_URLS: /dex
  AFTER_LOGOUT_URL: /
  USERID_HEADER: minio-service-userid
  USERID_PREFIX: ""
  USERID_CLAIM: email
  PORT: '"8080"'
  STORE_PATH: /var/lib/authservice/data.db

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oidc-authservice
  namespace: oidc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice
  serviceName: authservice
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: authservice
    spec:
      serviceAccountName: authservice
      containers:
      - name: authservice
        image: docker.io/kubeflowmanifestswg/oidc-authservice:e236439
        imagePullPolicy: IfNotPresent
        ports:
        - name: http-api
          containerPort: 8080
        envFrom:
        - secretRef:
            name: oidc-authservice-client
        - configMapRef:
            name: oidc-authservice-parameters
        volumeMounts:
        - mountPath: /var/lib/authservice
          name: data
        readinessProbe:
          httpGet:
            path: /
            port: 8081
      securityContext:
        fsGroup: 111
      volumes:
      - name: data
        persistentVolumeClaim:
            claimName: authservice-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: authservice
  namespace: oidc
spec:
  type: ClusterIP
  selector:
    app: authservice
  ports:
  - port: 8080
    name: http-authservice
    targetPort: http-api
  publishNotReadyAddresses: true