apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: minio-service
type: Opaque
data:
  .accesskey: bWluaW8uYWRtaW5AdGVjaHRlbC5jb20=
  .secretkey: bWluaW9hZG1pbg==
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: minio-service
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio-sa
  namespace: minio-service
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: minio-service
  labels:
    app: minio
    version: v1
spec:
  serviceName: minio
  selector:
    matchLabels:
      app: minio
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: minio
        version: v1
    spec:
      serviceAccountName: minio-sa
      containers:
      - name: minio
        image: quay.io/minio/minio
        imagePullPolicy: Always
        args:
        - server
        - /data
        - --console-address
        - :9001
        lifecycle:
          postStart:
            exec:
              command: 
              - "/bin/sh"
              - "-c"
              - |
                sleep 3s
                mc alias set minioserver $MINIO_HOST $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD --api "S3v4" --path "auto"
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
          limits: {}
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: .accesskey
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: .secretkey
        - name: MINIO_HOST
          value: http://localhost:9000
        - name: MINIO_IDENTITY_OPENID_DISPLAY_NAME
          value: "Login with SSO"
        - name: MINIO_IDENTITY_OPENID_CONFIG_URL
          value: "http://dex.auth.svc.cluster.local:5556/dex/.well-known/openid-configuration"
        - name: MINIO_IDENTITY_OPENID_CLIENT_ID
          value: "minio-client-app"
        - name: MINIO_IDENTITY_OPENID_CLIENT_SECRET
          value: "minio-client-app-secret"
        - name: MINIO_BROWSER_REDIRECT_URL
          value: "http://localhost:9001/oauth_callback"
        - name: MINIO_IDENTITY_OPENID_ROLE_POLICY
          value: "consoleAdmin"
        - name: MINIO_IDENTITY_OPENID_SCOPES
          value: "email"
        ports:
        - containerPort: 9000
        - containerPort: 9001
        volumeMounts:
        - mountPath: /data
          name: data
          subPath: minio
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minio-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: minio-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: console-port
    port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    app: minio
    version: v1